name: "Terraform Deployment for shared infrastructure Account"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
concurrency:
  group: infra-deploy
jobs:
  terraform:
    name:  Terraform Deployment-${{ matrix.environment }}
    runs-on: [ ubuntu-latest ]
    strategy:
      max-parallel: 1
      matrix:
        include:
            - environment: dev
    steps:
    - uses: actions/checkout@v5
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.INFRA_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.INFRA_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - uses: hashicorp/setup-terraform@v3
      with:
          terraform_wrapper: false
    - name: Terraform Init
      id: init
      run: |
        rm -rf .terraform
        terraform init -backend-config=${{ matrix.environment }}/backend.tfvars -upgrade=true -no-color -input=false
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -var-file=${{ matrix.environment }}/terraform.tfvars -no-color
    - name: Terraform apply
      if: github.ref == 'refs/heads/main'
      id: apply
      run: |
        terraform apply -var-file=${{ matrix.environment }}/terraform.tfvars -no-color --auto-approve=true
